### ISSUE TITLE
Autofill hints values

### ISSUE THREAD

**Issue by kusan-thana** [googlesamples/android-AutofillFramework#10]
Hi,

Is it possible to get a list of values for the hints in the doc?

There is "username" and "password" in the exemple but is "mail" correct?

I guess it depends on the providers, but then it's not standardized? Removes a bit the point of the API then, no... ?

Thanks,

**Comment by DougSig** [comment]
You can find the constants on the [reference doc](https://developer.android.com/reference/android/view/View.html#AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DATE) for View. Look for variables named with the pattern "View.AUTOFILL_HINT_*". The "Constant value" is what you should put for the "autofillHints" attribute in your XML.

**Comment by kusan-thana** [comment]
Thanks! Would be good to put it in the doc (https://developer.android.com/guide/topics/text/autofill.html) and to use the View constant values in the exemple code instead of writing it bare.

**Comment by the-felipeal** [comment]
This is already documented on https://developer.android.com/guide/topics/text/autofill.html#providing_hints_for_autofill : 


_The Autofill Framework does not validate the hints; they are just passed along as is to the autofill service. Hence, they can have any value, but it is recommended to use predefined values such as AUTOFILL_HINT_USERNAME for a username or AUTOFILL_HINT_CREDIT_CARD_NUMBER for a credit card number. For a list of all predefined autofill hint constants, see the View reference._
