### ISSUE TITLE
In Virtual View, username viewnode has AutofillValue type of date

### ISSUE THREAD

**Issue by dlarsonks** [googlesamples/android-AutofillFramework#11]
In the screen "Sample Login Using a Custom Virtual View", the username ViewNode has an AutofillValue type of date.  That is, for the username ViewNode,  viewNode.getAutofillValue().isDate() returns true.

**Comment by DougSig** [comment]
Fixed in latest push (https://github.com/googlesamples/android-AutofillFramework/commit/8ce9eb3815644ee2ed54232cc549e0546cf87448).
