### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by r9software** [googlesamples/android-AutofillFramework#17]
In this page: https://developer.android.com/guide/topics/ui/controls/pickers it sends to this page:
https://github.com/googlesamples/android-AutofillFramework/blob/master/Application/src/main/java/com/example/android/autofillframework/app/CreditCardExpirationDatePickerView.java

I could not find that page on the repo.

**Comment by the-felipeal** [comment]
That class was moved and the right link now is https://github.com/googlesamples/android-AutofillFramework/blob/master/Application/src/main/java/com/example/android/autofill/app/view/autofillable/CreditCardExpirationDatePickerView.java 

Thanks for reporting, we'll fix it

**Comment by jabubake** [comment]
Doc link is now fixed. Thanks.
