### ISSUE TITLE
sample code not working

### ISSUE THREAD

**Issue by pajingko** [googlesamples/android-AutofillFramework#4]
Android Studio show message : 
Error:Failed to find target with hash string 'android-O' in: /Users/xxx/Library/Android/sdk

When I click the _Install missing platform(s) and sync project_ link android studio show dialog message as below :

Packages Unavailable
All package are not available for download!
The following package are not available:
- Package id platforms; android-O

Thanks in advance.

**Comment by dandv** [comment]
I see you closed the issue. How did you solve the problem?

**Comment by DougSig** [comment]
Hi Dan,
Are you getting the same error?

**Comment by dandv** [comment]
I get a different error out of the box with 2.3.3: "This Gradle plugin requires Studio 3.0 minimum"

![image](https://user-images.githubusercontent.com/33569/27248099-067d59f6-52b4-11e7-8947-eaf794447bc1.png)

**Comment by DougSig** [comment]
Because O is still in preview, I felt empowered to make you use AS 3.0
preview. Probably not the best decision. Feel free to roll back the gradle
versions to work on your Studio environment.
