### ISSUE TITLE
Question: is there a sample for pre-Android-O ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-AutofillFramework#9]
As I remember, Google does offer a way to make auto-completion work for previous versions of Android, and not just Android O.
Or at least for phones.

Is there a sample for it?

**Comment by DougSig** [comment]
Hi,
Are you referring to the [AutoCompleteTextView](https://developer.android.com/reference/android/widget/AutoCompleteTextView.html)?

**Comment by AndroidDeveloperLB** [comment]
No. I'm talking about real auto-completion of user data.

**Comment by DougSig** [comment]
Do you have a link you can refer me to? The autofill framework is new as of Android O (API 26).

**Comment by DougSig** [comment]
You might be referring to autofill services that leverage the Accessibility framework?

**Comment by AndroidDeveloperLB** [comment]
No. It's by Google, and it works on various Android versions. I think it's mainly (or only) for auto-completion of phone number of the user.
Here:
https://www.youtube.com/watch?v=MUULwaxqFLI&feature=youtu.be&t=1284

**Comment by DougSig** [comment]
Hi,
Thanks for following up. That video talks about phone authentication. The part you linked to talks about the auto-retrieval feature of the [Firebase phone auth API](https://firebase.google.com/docs/auth/android/phone-auth). If that's what you're interested in, you can find a snippet on the page. The demo on the video looks like it uses FirebaseUI for the phone number widget.

Not related to your link, but you also might be referring to https://developers.google.com/identity/smartlock-passwords/android/. There should be enough detail on that page to get you started.
